openapi: "3.0.0"
info:
  version: 1.0.0
  title: Forest api
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
  /tree:
    get:
      summary: List all trees
      operationId: listTrees
      tags:
        - tree
      responses:
        '200':
          description: A tree list was found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tree"
    post:
      summary: Create a tree
      operationId: create_tree
      tags:
        - tree
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tree'
      responses:
        '201':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tree'
    put:
      summary: Update a tree
      operationId: update_tree
      tags:
        - tree
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tree'
      responses:
        '200':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tree'

  /tree/{id}:
    get:
      summary: Info for a tree
      operationId: getTree
      tags:
        - tree
      parameters:
        - name: id
          in: path
          required: true
          description: The tree id
          schema:
            type: string
      responses:
        '200':
          description: A tree was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tree"
    delete:
      tags:
        - tree
      summary: Delete a tree.
      operationId: delete_tree
      parameters:
        -
          in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Tree has been deleted.
          content:
            application/json:
              schema:
                type: string
                description: ID of the deleted entity.

  /forest:
    get:
      summary: List all forest
      operationId: list_forest
      tags:
        - forest
      responses:
        '200':
          description: A forest list was found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Forest"
    post:
      summary: Create a forest
      operationId: create_forest
      tags:
        - forest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Forest'
      responses:
        '201':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forest'
    put:
      summary: Update a forest
      operationId: update_forest
      tags:
        - forest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Forest'
      responses:
        '200':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forest'

  /forest/{id}:
    get:
      summary: Info for a forest
      operationId: getForest
      tags:
        - forest
      parameters:
        -
          name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
      responses:
        '200':
          description: A forest was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forest"
    delete:
      tags:
        - tree
      summary: Delete a forest.
      operationId: delete_forest
      parameters:
        -
          in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Forest has been deleted.
          content:
            application/json:
              schema:
                type: string
                description: ID of the deleted entity.

components:
  schemas:
    Species:
      enum:
        - OAK
        - EVERGREEN_OAK
        - FIR
        - ASH
        - BEECH
    Exposure:
      enum:
        - SUNNY
        - MID_SHADOW
        - SHADOW
    Tree:
      required:
        - id
        - birth
        - species
        - exposure
        - carbonStorageCapacity
      properties:
        id:
          type: string
          format: uuid
        birth:
          type: string
          format: date
        exposure:
          $ref: '#/components/schemas/Exposure'
        species:
          $ref: '#/components/schemas/Species'
        carbonStorageCapacity:
          type: number
          format: double
    ForestType:
      enum:
        - BOREAL
        - TEMPERATE
        - TROPICAL
    Forest:
      required:
        - id
        - type
        - trees
        - surface
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/ForestType'
        trees:
          type: array
          additionalProperties: false
          items:
            type: object
        surface:
          type: number